### ISSUE TITLE
Changes for moe

### ISSUE THREAD

**Issue by fpunny** [hackthevalley/htv4-landing#1]
- [x] Update email to sponsorships@hackthevalley.io
- [ ] Add "COMING SOON Fall 2021" above FAQ
- [x] Remove HT4 specific content
- [x] Hide sponsors/schedule

**Comment by moyoonthego** [comment]
Looks good, if we can make a visual banner coming soon instead of adding it to the about and footer, that's would look really nice. Unless it will take a lot of time. I just thought we could use an online animation pack and be done with it in in a minute
